basePath: /
host: localhost:8000
info:
  contact:
    email: raulmfranca@gmail.com
    name: Raul França
    url: https://github.com/raul-franca
  description: Modulo API do curso full cycle
  license:
    name: Name License
    url: https://github.com/raul-franca
  termsOfService: http://swagger.io/terms/
  title: go-fc-api
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
